---
title: "Prepare data"
author: "Stefano Coretta"
format: html
editor: source
---

## Read data

```{r}
#| label: setup

library(tidyverse)

```

```{r}
#| label: beckerkristal2010-wide

beckerkristal2010_wide <- readxl::read_xls(
  "BeckerVowelCorpus.xls",
  sheet = 1
) |> 
  # Mutate some chr cols to num
  mutate(
    across(matches("F\\d"), function(x) ifelse(x == "XXX", NA, x)),
    across(matches("F\\d"), as.numeric),
    `#Speakers` = ifelse(`#Speakers` == "?", NA, `#Speakers`),
    `#Speakers` = as.numeric(`#Speakers`)
  ) |> 
  # Drop empty column
  select(-`...98`) |> 
  drop_na(Language)

col_names <- colnames(beckerkristal2010_wide)
sub_names <- c(
  "iso_639_3", "language", "variety", "genetics",
  "source", "n_speakers", "method", "quantity",
  "harmony", "n_vowels", "structure",
  "n_peripheral", "n_nonperipheral"
)
col_names[1:13] <- sub_names
colnames(beckerkristal2010_wide) <- col_names

beckerkristal2010_wide <- beckerkristal2010_wide |> 
  mutate(
    symmetry = str_extract(structure, "[SLR]"),
    quantity = str_to_sentence(quantity),
    quantity = str_replace(quantity, "Conbined", "Combined"),
    harmony = str_to_sentence(harmony)
  ) |> 
  relocate(symmetry, .after = n_peripheral)
```

## Long format

```{r}
#| label: beckerkristal2010

beckerkristal2010 <- beckerkristal2010_wide |> 
  pivot_longer(
    V1OS:V14F4,
    names_to = c("vowel_id", "suffix"),
    names_pattern = "V(\\d{1,2})(.*)",
    values_transform = as.character
  ) |> 
  pivot_wider(
    names_from = "suffix"
  ) |> 
  # drop non-existing vowels
  drop_na(F1) |> 
  mutate(
    across(F1:F4, as.numeric),
    vowel_num = as.numeric(vowel_id),
    vowel_id = paste0("V", vowel_id)
  )
```


## Save data

```{r}
#| label: save

usethis::use_data(beckerkristal2010_wide, overwrite = TRUE)
usethis::use_data(beckerkristal2010, overwrite = TRUE)
```

